### DISCUSSION TITLE
swing horizontal and vertical

### DISCUSSION THREAD

**Discussion by dgalfy** [lumixen/esphome-hlink-ac#17] [Q&A] [answered]
Hi,

thanks lumixen for your work, I've been waiting 4 years for someone to do this :)

I have a Hitachi Shirokuma (RAK-35RXE) air conditioner. It can move the baffles both horizontally and vertically. 
I checked with datalogger, at address P0014 I detected the following:
0x00= no swing
0x01= vertical
0x02= horizontal
0x03= horizontal and vertical

Could this be implemented in the code somehow?

_Translated with DeepL.com (free version)_

**Comment by lumixen** [comment, marked as answer]
Hi @dgalfy,

Thank you for the debug data!

Please try the changes in the `horizontal-swing-mode` [branch](https://github.com/lumixen/esphome-hlink-ac/tree/horizontal-swing-mode). I decided to keep the `OFF` and `VERTICAL` swing options as the default ones if no additional configuration is provided, so in order to make the `horizontal` and `both` swing options available in Home Assistant you will need to explicitly list all of them in the climate configuration:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/lumixen/esphome-hlink-ac.git
      ref: horizontal-swing-mode
    refresh: 0s
    components: [hlink_ac]

climate:
  - platform: hlink_ac
    name: "HITACHI AC"
    hvac_actions: true
    supported_presets:
      - AWAY
    supported_swing_modes:
      - "OFF"
      - VERTICAL
      - HORIZONTAL
      - BOTH
```

Let me know if the new options work as expected and nothing is broken for you (I don't have available for testing device that supports horizontal swinging) and I will proceed with making a new release.
