### DISCUSSION TITLE
Temperature step

### DISCUSSION THREAD

**Discussion by clsergent** [lumixen/esphome-hlink-ac#23] [Ideas]
# Setup
esphome-hlink-ac version: 2025.3
target: RAK-DJ50RHAE / RAK-DJ18RHAE

# Rationale
Visual temperature step is supposed to be a multiple of 1. However it seems that the AC can handle 0.5 increments as the IR remote steps are 0.5°C.

In addition, Home Assistant can handle arbitrary temperature steps through customize:
```
homeassistant:
  customize:
    climate.thermostat_entity:
      target_temp_step: 0.5
```

Would it be possible to relax this check?

# Full error log (ESPHome check):
```
Configured visual temperature step 0.5 is wrong, it should be a multiple of 1.
  platform: hlink_ac
  name: RAK-DJ18RHAE
  hvac_actions: True
  supported_presets: 
    - AWAY
  visual: 
    min_temperature: 16.0
    max_temperature: 32.0
    temperature_step: 
      target_temperature: 0.5
      current_temperature: 1.0
```
